# Generated by Django 5.0.9 on 2026-03-05 01:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator(message='Spotify IDs must be 22 alphanumeric characters.', regex='^[A-Za-z0-9]{22}$')])),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['spotify_id'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22, validators=[django.core.validators.RegexValidator(message='Spotify IDs must be 22 alphanumeric characters.', regex='^[A-Za-z0-9]{22}$')])),
                ('name', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'spotify_id'],
            },
        ),
        migrations.CreateModel(
            name='TrackInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='music.playlist')),
                ('sublist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedded_entries', to='music.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='music.track')),
            ],
            options={
                'ordering': ['playlist', 'position'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='music.TrackInPlaylist', to='music.track'),
        ),
        migrations.AddConstraint(
            model_name='trackinplaylist',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='unique_position_in_playlist'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('owner', 'spotify_id'), name='unique_owner_playlist_spotify_id'),
        ),
    ]
