# Generated by Django 5.0.9 on 2026-03-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='track',
            name='uri',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
