# Generated by Django 5.0.9 on 2026-03-18 02:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_uri_artists_album'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_spotify_id', models.CharField(max_length=22, validators=[django.core.validators.RegexValidator(message='Spotify IDs must be 22 alphanumeric characters.', regex='^[A-Za-z0-9]{22}$')])),
                ('current_track_uri', models.CharField(max_length=100)),
                ('position_ms', models.PositiveIntegerField(default=0)),
                ('track_uris', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='listeningsession',
            constraint=models.UniqueConstraint(fields=('owner', 'playlist_spotify_id'), name='unique_owner_playlist_session'),
        ),
    ]
