# Generated by Django 5.0.9 on 2026-03-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_listeningsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsession',
            name='shuffled',
            field=models.BooleanField(default=False),
        ),
    ]
